let
  system = ../../modules/system/nixos;
  systemShared = ../../modules/system/shared;
  homeShared = ../../modules/home-manager/shared;
  homeLinux = ../../modules/home-manager/linux;
in {
  imports = [
    ./hardware-configuration.nix
    (systemShared + /packages.nix)
    (system + /app-images.nix)
    (system + /audio.nix)
    (system + /bluetooth.nix)
    (system + /boot.nix)
    # (system + /docker.nix)
    (system + /fonts.nix)
    (system + /graphics.nix)
    (system + /home-manager.nix)
    (system + /internationalisation.nix)
    (system + /jellyfin.nix)
    (system + /liquidctl.nix)
    (system + /networking.nix)
    (system + /nix-settings.nix)
    # (system + /ollama.nix)
    # (system + /openvpn.nix)
    (system + /polkit.nix)
    (system + /printing.nix)
    (system + /nix-ld.nix)
    (system + /security.nix)
    (system + /session-variables.nix)
    (system + /steam.nix)
    (system + /stylix.nix)
    (system + /system.nix)
    (system + /system-packages.nix)
    # (system + /tandoor-recipes.nix)
    (system + /ttyd)
    # (system + /mattermost.nix)
    # (system + /stirling-pdf.nix)
    # (system + /thunar)
    (system + /virtualization.nix)
    (system + /wireguard-client.nix)
    (system + /wordpress.nix)
    (system + /xdg-portal.nix)
    (system + /ydotool.nix)
  ];

  home-manager.users.nicolas.imports = [
    # (homeShared + /atuin)
    (homeShared + /bash)
    (homeShared + /bat)
    (homeShared + /btop)
    (homeShared + /claude-code)
    (homeShared + /dircolors)
    (homeShared + /direnv)
    (homeShared + /eza)
    (homeShared + /fastfetch)
    (homeShared + /fd)
    (homeShared + /fzf)
    (homeShared + /ghostty)
    (homeShared + /git)
    (homeShared + /htop)
    (homeShared + /jq)
    (homeShared + /kitty)
    (homeShared + /neovim)
    (homeShared + /nix-search.nix)
    (homeShared + /oh-my-posh)
    (homeShared + /opencode)
    (homeShared + /ripgrep)
    (homeShared + /ssh.nix)
    (homeShared + /thunderbird)
    (homeShared + /tmux.nix)
    (homeShared + /zoxide.nix)
    (homeLinux + /default-applications.nix)
    # (homeLinux + /dropbox.nix)
    (homeLinux + /files)
    (homeLinux + /gitui.nix)
    (homeLinux + /gtk-qt.nix)
    (homeLinux + /hyprland)
    # (homeLinux + /mouseless.nix)
    # (homeLinux + /obs.nix)
    (homeLinux + /others.nix)
    (homeLinux + /packages.nix)
    # (homeLinux + /qutebrowser.nix)
    # (homeLinux + /ranger.nix)
    (homeLinux + /rofi)
    (homeLinux + /stylix-targets.nix)
    (homeLinux + /swappy.nix)
    (homeLinux + /swaync.nix)
    (homeLinux + /waybar)
    # (homeShared + /zellij.nix)
  ];
}
